import streamlit as st

st.markdown(
    """
    # Approach #1 (Pruning the Model + Circuit Identities and Optimization)


    One of our other approaches was to begin by tackling the circuit directly. We noticed that there were a bunch of rotation gates that were being generated by the Qiskit code that were not actually rotating anything. So, we began by pruning these gates out immediately leading to a reduced factor in the depth of the circuit. Notably, the following is an image of the original circuit with the additional rotation gates.

    ![Default Circuit](https://i.ibb.co/QP4jy9v/2.png)

    The following was the reduced circuit after the described pruning operation. As can be seen, we offer quite an improved design that doesn’t rely on these additional gates (which produce a large amount of error unnecessarily, since this is usually the case with single / two-qubit gates), and it results in slightly better results compared to the previous one, as will be seen in the graph at the end.

    ![Default Circuit](https://i.ibb.co/q5zp3GV/3.png)
    
    After doing this, we noticed that we can start applying different gate identities and start replacing the two-circuit gates with other versions, so as to potentially improve the circuit, however we didn’t have any luck with reducing the circuit further. As an example, we considered replacing the c-NOT gates with the following rotation gates and simply re-writing the rotation gates as a single rotate gate, which is possible.
    
    ![Default Circuit](https://i.ibb.co/zGcPQCD/4.png)
    
    We also thought about using different c-NOT operations where we can flip the order of different rotation gates and c-NOTs or swap the order of c-NOT gates themselves. These identities can be seen below, which can be useful in helping to properly stagger c-NOT gates and then ultimately use something like teleportation to create a teleportation circuit of smaller depth.

    ![Default Circuit](https://i.ibb.co/tz4JF0C/5.png)
    
    Consider the following below snippet of the beginning of the circuit of us beginning to implement this possibility.
    
    ![Default Circuit](https://i.ibb.co/517wFZX/6.png)

    As can be seen from the above image, we have replaced the c-NOT gates with their corresponding rotation versions. Unfortunately, due to time constraints, we were unable to continue to reduce the circuit down which would be possible by combining the rotation gates further. We also read a paper that would allow us to re-write two-qubit X rotation gates as that of a quantum teleportation circuit, which we could potentially further improve the above circuit by introducing additional ancillae.
    
    ![Default Circuit](https://i.ibb.co/fnwRChT/7.png)

    The following are our results from running the simulation. The selections Noisy1 - Noisy3 correspond to each progressive iteration of the circuit. As can be seen, it largely stays the same, but there are definitely some improvements to be made and simplify the circuit in the last case, where we see more significant error rates due to there being a lot more rotation gates. However, this would be something we could improve through simplification and teleportation. We just ran out of time to do all of it. :(

    """
)